[package]
name = "aral"
description = "Async Runtime Aggregation Layer."
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
repository = { workspace = true }
license = { workspace = true }

[features]
runtime-tokio-current-thread = ["tokio"]
runtime-tokio-multi-thread = ["tokio", "tokio/rt-multi-thread"]
runtime-async-std = ["async-std"]

[dependencies]
async-std = { version = "1.12.0", optional = true }
cfg-if = "1.0.0"
tokio = { version = "1.28.1", features = ["fs", "io-util", "net", "time", "rt"], optional = true }
