name: Publish

on:
  push:
    tags: [ "**" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"
  RUSTFLAGS: "-D warnings"
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

jobs:
  publish:
    name: Publish

    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cargo publish aral-runtime-noop
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p aral-runtime-noop
        continue-on-error: true

      - name: Cargo publish aral-runtime-tokio
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p aral-runtime-tokio
        continue-on-error: true

      - name: Cargo publish aral-runtime-async-std
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p aral-runtime-async-std
        continue-on-error: true

      - name: Cargo publish aral
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: -p aral
        continue-on-error: true
